# Install Apache webserver playbook
---
  - hosts: backend:frontend
    become: True
    tasks:
      - name: Install Apache server
        apt: name=apache2 state=present
      - name: Delete index.html file
        file: path=/var/www/html/index.html state=absent
      - name: Create new index.hml file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html><head><title>Hello World</title></head><body><h1>Hello from Server1</h1></body></html>