# Read password stored in Ansible-Vault
---
  - hosts: local
    vars_files:
      - ./secrets.yml
    tasks:
      - name: Retrieve encrypted password
        debug:
          msg: "{{ test_password }}"